name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.targets.outputs.targets }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare overrides
        run: |
          echo "$DOCKER_BAKE_OVERRIDE" >docker-bake.override.hcl
        env:
          DOCKER_BAKE_OVERRIDE: ${{ vars.DOCKER_BAKE_OVERRIDE }}

      - name: Get targets
        id: targets
        uses: docker/bake-action/subaction/list-targets@v6

  publish:
    name: ${{ matrix.target }}
    needs:
      - prepare
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare.outputs.targets) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare overrides
        run: |
          echo "$DOCKER_BAKE_OVERRIDE" >docker-bake.override.hcl
        env:
          DOCKER_BAKE_OVERRIDE: ${{ vars.DOCKER_BAKE_OVERRIDE }}

      - name: Bake image
        uses: docker/bake-action@v6
        with:
          allow: security.insecure
          push: true
          source: .
          targets: ${{ matrix.target }}
        env:
          DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}

      - name: Update description on Docker Hub
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
