name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare overrides
        run: |
          echo "$DOCKER_BAKE_OVERRIDE" >docker-bake.override.hcl
        env:
          DOCKER_BAKE_OVERRIDE: ${{ vars.DOCKER_BAKE_OVERRIDE }}

      - name: Bake image
        uses: docker/bake-action@v5
        with:
          allow: security.insecure
          push: true
        env:
          DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}

      - name: Update description on Docker Hub
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
